
// redux saga to hnadle async functions
export const EMAIL_SIGN_IN_START = "EMAIL_SIGN_IN_START"
export const SIGN_IN_SUCCESSFUL = "SIGN_IN_SUCCESSFUL"
export const CHECK_USER_SESESION = "CHECK_USER_SESESION"
export const SIGN_UP_USER_START = "SIGN_UP_USER_START"
export const SIGN_OUT_USER_START = "SIGN_OUT_USER_START"
export const SIGN_OUT_USER_SUCCESS = "SIGN_OUT_USER_SUCCESS"
export const USER_ERROR = 'USER_ERROR'
export const RESET_PASSWORD_START = 'RESET_PASSWORD_START'



// redux thunk
export const CURRENT_USER = "CURRENT_USER"
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR"
export const SIGN_IN_ERROR = "SIGN_IN_ERROR"
export const RESET_AUTH ="RESET_AUTH"